USE [PHONE]
GO
/****** Object:  StoredProcedure [dbo].[HSX_TEN_HINHANH]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--Hãng sản xuất--

CREATE PROC [dbo].[HSX_TEN_HINHANH] (@LENH INT)
AS
	IF(@LENH = 1)
	BEGIN
		SELECT * FROM HANGSANXUAT ORDER BY THUTU
	END
	IF(@LENH = 2)
	BEGIN
		SELECT * FROM HANGSANXUAT A,MENU B  WHERE A.MAHSX = B.MAHSX ORDER BY A.THUTU
	END
--hỗ trợ--

GO
/****** Object:  StoredProcedure [dbo].[HT]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[HT](@LENH INT)
AS
	IF(@LENH = 1)
		SELECT * FROM HOTRO ORDER BY THUTU

GO
/****** Object:  StoredProcedure [dbo].[SP_CAP_NHAT_NDGUI]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Nội dung gửi mail --
CREATE PROC [dbo].[SP_CAP_NHAT_NDGUI](@KICHHOAT INT, @COKICHHOAT NTEXT, @KOCOKICHHOAT NTEXT, @RESETMATKHAU NTEXT)
AS
	BEGIN
		UPDATE NDGUI
		SET KICHHOAT = @KICHHOAT, COKICHHOAT = @COKICHHOAT, KOCOKICHHOAT = @KOCOKICHHOAT, RESETMATKHAU = @RESETMATKHAU
	END

GO
/****** Object:  StoredProcedure [dbo].[SP_CTSP]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_CTSP](@MASP INT, @LENH INT)
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM SANPHAM WHERE ANHIEN = 1 AND MASP = @MASP
		END
	IF(@LENH = 2)
		BEGIN
			SELECT * FROM HINHANHCHITIET WHERE MASP = @MASP
		END
	IF(@LENH = 4)
		BEGIN
			SELECT * FROM MAUSANPHAM A , MAU B WHERE A.MAMAU = B.MAMAU AND MASP = @MASP
		END
	IF(@LENH = 5)
		BEGIN
			SELECT CODEXOAY360 FROM SANPHAM WHERE ANHIEN = 1 AND MASP = @MASP
		END
	IF(@LENH = 6)
		BEGIN
			SELECT B.HINHANH,NOIDUNGKM FROM SANPHAM A,TRANGTHAI B, KHUYENMAI C WHERE A.MASP = C.MASP AND B.MATT=C.MATT  AND ANHIEN = 1 AND C.NGAYBATDAU <= GETDATE() AND GETDATE() <= C.NGAYKETTHUC AND C.NGAYBATDAU >= A.NGAYBATDAU AND A.MASP = @MASP 
		END
	IF(@LENH = 7)
		BEGIN
			SELECT MOTA FROM SANPHAM WHERE ANHIEN = 1 AND MASP = @MASP
		END
	IF(@LENH = 8)
		BEGIN
			SELECT TINHNANGCHITIET FROM SANPHAM WHERE ANHIEN = 1 AND MASP = @MASP
		END
	IF(@LENH = 9)
		BEGIN
			SELECT TOP(11) * FROM SANPHAM WHERE ANHIEN = 1
		END
	IF(@LENH = 11)
		BEGIN
			UPDATE SANPHAM SET LUOTXEM = (LUOTXEM + 1) WHERE MASP = @MASP
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_DANG_KY]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Đăng ký khách hàng --
CREATE PROC [dbo].[SP_DANG_KY](@HOKH NVARCHAR(50), @TENKH NVARCHAR(50), @EMAIL VARCHAR(50), @MATKHAU VARCHAR(50),@DIACHI VARCHAR(50), @DIENTHOAI VARCHAR(15), @NGAYDANGKY SMALLDATETIME, @NGAYCAPNHAT SMALLDATETIME, @MAKICHHOAT VARCHAR(20), @KICHHOAT BIT, @ANHIEN BIT, @LENH INT)
AS
	IF(@LENH = 1)
		BEGIN
			INSERT INTO KHACHHANG VALUES (@HOKH, @TENKH, @EMAIL, @MATKHAU, @DIACHI, @DIENTHOAI, @NGAYDANGKY, @NGAYCAPNHAT, @MAKICHHOAT, @KICHHOAT, @ANHIEN)
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_DANG_NHAP_QUANTRI]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- **************** Phần Admin **************** --
-- Đăng nhập quản trị -- 
CREATE PROC [dbo].[SP_DANG_NHAP_QUANTRI](@LENH INT, @TAIKHOAN VARCHAR(30), @MATKHAU VARCHAR(30))
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM QUANLYWEB WHERE TAIKHOAN = @TAIKHOAN AND MATKHAU = @MATKHAU AND ANHIEN = 1
		END
	IF(@LENH = 2)
		BEGIN
			UPDATE QUANLYWEB
			SET NGAYTRUYCAP = GETDATE()
			WHERE TAIKHOAN = @TAIKHOAN
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_DANH_MUC_TRANG]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Danh mục trang --
CREATE PROC [dbo].[SP_DANH_MUC_TRANG](@LENH INT)
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM DANHMUCTRANG
		END
	IF(@LENH = 2)
		BEGIN 
			SELECT MATRANG, TIEUDE FROM DANHMUCTRANG
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_DDH]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_DDH](@LENH INT, @MADH INT, @NGAYDATHANG SMALLDATETIME, @TENNGUOINHAN NVARCHAR(30), @DIACHINHAN NVARCHAR(500), @DIENTHOAINHAN VARCHAR(15), @MATINHTRANG INT)
AS
	IF(@LENH = 1)
		BEGIN
			UPDATE DONDATHANG
			SET TENNGUOINHAN = @TENNGUOINHAN, DIACHINHAN = @DIACHINHAN, DIENTHOAINHAN = @DIENTHOAINHAN, NGAYDATHANG = @NGAYDATHANG
			WHERE MADH = @MADH
		END
	IF(@LENH = 2)
		BEGIN
			UPDATE DONDATHANG
			SET MATINHTRANG = @MATINHTRANG
			WHERE MADH = @MADH
		END
	IF(@LENH = 3)
		BEGIN
			SELECT * FROM DONDATHANG A, KHACHHANG B WHERE A.MAKH = B.MAKH AND MADH = @MADH
		END
	IF(@LENH = 4)
		BEGIN
			SELECT * FROM CHITIETDATHANG A, SANPHAM B WHERE A.MASP = B.MASP AND MADH = @MADH
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_HDH]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- HDH --
CREATE PROC [dbo].[SP_HDH](@LENH INT, @MAHDH INT, @TENHDH NVARCHAR(30), @ANHIEN BIT)
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM HEDIEUHANH
		END
	-- Thêm --
	IF(@LENH = 2)
		BEGIN
			INSERT INTO HEDIEUHANH VALUES(@TENHDH, @ANHIEN)
		END
	-- Sửa --
	IF(@LENH = 3)
		BEGIN
			UPDATE HEDIEUHANH
			SET TENHDH = @TENHDH, ANHIEN = @ANHIEN
			WHERE MAHDH = @MAHDH
		END
	-- Xóa --
	IF(@LENH = 4)
		BEGIN
			DELETE HEDIEUHANH WHERE MAHDH = @MAHDH
		END
	-- Cập nhật ẩn hiện --
	IF(@LENH = 5)
		BEGIN
			UPDATE HEDIEUHANH
			SET ANHIEN = @ANHIEN
			WHERE MAHDH = @MAHDH
		END
	IF(@LENH = 6)
		BEGIN
			SELECT * FROM HEDIEUHANH WHERE MAHDH = @MAHDH
		END
	IF(@LENH = 7)
		BEGIN
			SELECT MAHDH, TENHDH FROM HEDIEUHANH WHERE ANHIEN = 1
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_HINH_ANH_CHI_TIET]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Hình ảnh chi tiết --
CREATE PROC [dbo].[SP_HINH_ANH_CHI_TIET](@LENH INT, @MASP INT, @HINHANH VARCHAR(255), @HINHANHNEW VARCHAR(255))
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM HINHANHCHITIET WHERE MASP = @MASP
		END
	-- Thêm --
	IF(@LENH = 2)
		BEGIN
			INSERT INTO HINHANHCHITIET VALUES(@MASP, @HINHANH)
		END
	-- Sửa --
	IF(@LENH = 3)
		BEGIN
			UPDATE HINHANHCHITIET
			SET HINHANH = @HINHANHNEW
			WHERE MASP = @MASP AND HINHANH = @HINHANH
		END
	-- Xóa --
	IF(@LENH = 4)
		BEGIN
			DELETE FROM HINHANHCHITIET WHERE MASP = @MASP AND HINHANH = @HINHANH
		END
	-- kiểm tra hình ảnh --
	IF (@LENH = 5)
		BEGIN
			SET @HINHANH = (SELECT HINHANH FROM SANPHAM WHERE MASP = @MASP)
			INSERT INTO HINHANHCHITIET VALUES(@MASP, @HINHANH)
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_HSX]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Hãng sản xuất --
CREATE PROC [dbo].[SP_HSX](@LENH INT, @MAHSX INT, @TENHSX NVARCHAR(30), @HINHANH VARCHAR(MAX), @THUTU INT, @ANHIEN BIT)
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM HANGSANXUAT
		END
	-- Thêm --
	IF(@LENH = 2)
		BEGIN
			INSERT INTO HANGSANXUAT VALUES(@TENHSX, @HINHANH, @THUTU, @ANHIEN)
		END
	-- Sửa --
	IF(@LENH = 3)
		BEGIN
			IF(@HINHANH = '')
				BEGIN
					SET @HINHANH = (SELECT HINHANH FROM HANGSANXUAT WHERE MAHSX = @MAHSX)
				END
			UPDATE HANGSANXUAT
			SET TENHSX = @TENHSX, HINHANH = @HINHANH, THUTU = @THUTU, ANHIEN = @ANHIEN
			WHERE MAHSX = @MAHSX
		END
	-- Xóa --
	IF(@LENH = 4)
		BEGIN
			DELETE HANGSANXUAT WHERE MAHSX = @MAHSX
		END
	-- Cập nhật ẩn hiện --
	IF(@LENH = 5)
		BEGIN
			UPDATE HANGSANXUAT
			SET ANHIEN = @ANHIEN
			WHERE MAHSX = @MAHSX
		END
	IF(@LENH = 6)
		BEGIN
			SELECT * FROM HANGSANXUAT WHERE MAHSX = @MAHSX
		END
	IF(@LENH = 7)
		BEGIN
			SELECT MAHSX, TENHSX FROM HANGSANXUAT WHERE ANHIEN = 1
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_KH]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

---Khách Hàng---
CREATE PROC [dbo].[SP_KH](@MAKH INT, @EMAIL VARCHAR(50), @MATKHAU VARCHAR(50), @LENH INT)
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM KHACHHANG WHERE ANHIEN = 1
		END
	-- Đăng nhập --
	IF(@LENH = 2)
		BEGIN
			SELECT * FROM KHACHHANG WHERE EMAIL = @EMAIL AND MATKHAU = @MATKHAU
		END
	IF(@LENH = 3)
		BEGIN
			SELECT * FROM KHACHHANG WHERE ANHIEN = 1 AND MAKH = @MAKH
		END
	IF(@LENH = 4)
		BEGIN
			SELECT * FROM KHACHHANG WHERE EMAIL = @EMAIL
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_KH_QT]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Khách hàng --
CREATE PROC [dbo].[SP_KH_QT](@LENH INT, @MAKH INT, @HOKH NVARCHAR(50), @TENKH NVARCHAR(50), @EMAIL VARCHAR(50), @MATKHAU VARCHAR(50), @DIACHI NVARCHAR(MAX), @DIENTHOAI VARCHAR(15), @NGAYDANGKY SMALLDATETIME, @NGAYCAPNHAT SMALLDATETIME, @MAKICHHOAT NVARCHAR(50), @KICHHOAT BIT, @ANHIEN BIT)
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM KHACHHANG
		END
	-- Thêm --
	IF(@LENH = 2)
		BEGIN
			INSERT INTO KHACHHANG VALUES (@HOKH, @TENKH, @EMAIL, @MATKHAU, @DIENTHOAI, @DIACHI, @NGAYDANGKY, @NGAYCAPNHAT, @MAKICHHOAT, @KICHHOAT, @ANHIEN)
		END
	-- Đổi mật khẩu --
	IF(@LENH = 3)
		BEGIN
			UPDATE KHACHHANG
			SET MATKHAU = @MATKHAU
			WHERE MAKH = @MAKH
		END
	-- Xóa --
	IF(@LENH = 4)
		BEGIN
			DELETE FROM KHACHHANG WHERE MAKH = @MAKH
		END
	-- Cập nhật ẩn hiện --
	IF(@LENH = 5)
		BEGIN
			UPDATE KHACHHANG
			SET ANHIEN = @ANHIEN
			WHERE MAKH = @MAKH
		END

GO
/****** Object:  StoredProcedure [dbo].[SP_KHUYENMAI]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Khuyến mãi --
CREATE PROC [dbo].[SP_KHUYENMAI](@LENH INT, @MAKM INT, @MASP INT, @MATT INT, @NOIDUNGKM NTEXT, @NGAYBATDAU SMALLDATETIME, @NGAYKETTHUC SMALLDATETIME)
AS
	IF(@LENH = 1)
		BEGIN
			SELECT A.*, TENSP, C.* FROM KHUYENMAI A, SANPHAM B, TRANGTHAI C WHERE A.MASP = B.MASP AND A.MATT = C.MATT
		END
	IF(@LENH = 2)
		BEGIN
			SELECT NGAYBATDAU FROM SANPHAM WHERE MASP = @MASP
		END
	IF(@LENH = 3)
		BEGIN
			SELECT A.*, B.TENSP, B.NGAYBATDAU FROM KHUYENMAI A, SANPHAM B WHERE A.MASP = B.MASP AND A.MAKM = @MAKM
		END
	IF(@LENH = 4)
		BEGIN
			SELECT MASP, TENSP FROM SANPHAM WHERE (((GETDATE() >= NGAYBATDAU) AND (GETDATE() <= NGAYKETTHUC) AND (NGAYKETTHUC IS NOT NULL)) OR ((GETDATE() >= NGAYBATDAU) AND (NGAYKETTHUC IS NULL))) AND ANHIEN = 1 AND MASP NOT IN (SELECT MASP FROM KHUYENMAI) ORDER BY TENSP
		END
	IF(@LENH = 5)
		BEGIN
			INSERT INTO KHUYENMAI(MASP,MATT,NOIDUNGKM,NGAYBATDAU,NGAYKETTHUC) VALUES(@MASP, @MATT, @NOIDUNGKM, @NGAYBATDAU, @NGAYKETTHUC)
		END
	IF(@LENH = 6)
		BEGIN
			UPDATE KHUYENMAI
			SET MATT = @MATT, NOIDUNGKM = @NOIDUNGKM, NGAYBATDAU = @NGAYBATDAU, NGAYKETTHUC = @NGAYKETTHUC
			WHERE MAKM = @MAKM
		END
	IF(@LENH = 7)
		BEGIN
			DELETE FROM KHUYENMAI WHERE MAKM = @MAKM
		END
	IF (@LENH = 8)
		BEGIN
			SELECT * FROM TRANGTHAI
		END

--- IN REPORT ------

GO
/****** Object:  StoredProcedure [dbo].[SP_KICH_HOAT_TAI_KHOAN]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Kích hoạt tài khoản --
CREATE PROC [dbo].[SP_KICH_HOAT_TAI_KHOAN](@MAKH INT, @MAKICHHOAT NVARCHAR(50), @LENH INT)
AS
	IF(@LENH = 1)
		BEGIN
			UPDATE KHACHHANG
			SET KICHHOAT = 1
			WHERE MAKH = @MAKH AND MAKICHHOAT = @MAKICHHOAT
		END
	IF(@LENH = 2)
		BEGIN
			SELECT * FROM KHACHHANG WHERE MAKH = @MAKH
		END
-- Tin tức --

GO
/****** Object:  StoredProcedure [dbo].[SP_KTMH]    Script Date: 06/22/2014 12:08:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- KTMH --
CREATE PROC [dbo].[SP_KTMH](@LENH INT, @MAKTMH INT, @TENKTMH NVARCHAR(30), @ANHIEN BIT)
AS
	IF(@LENH = 1)
		BEGIN
			SELECT * FROM KICHTHUOCMH
		END
	-- Thêm --
	IF(@LENH = 2)
		BEGIN
			INSERT INTO KICHTHUOCMH VALUES(@TENKTMH, @ANHIEN)
		END
	-- Sửa --
	IF(@LENH = 3)
		BEGIN
			UPDATE KICHTHUOCMH
			SET TENKTMH = @TENKTMH, ANHIEN = @ANHIEN
			WHERE MAKTMH = @MAKTMH
		END
	-- Xóa --
	IF(@LENH = 4)
		BEGIN
			DELETE KICHTHUOCMH WHERE MAKTMH = @MAKTMH
		END
	-- Cập nhật ẩn hiện --
	IF(@LENH = 5)
		BEGIN
			UPDATE KICHTHUOCMH
			SET ANHIEN = @ANHIEN
			WHERE MAKTMH = @MAKTMH
		END
	IF(@LENH = 6)
		BEGIN
			SELECT * FROM KICHTHUOCMH WHERE MAKTMH = @MAKTMH
		END
	IF(@LENH = 7)
		BEGIN
			SELECT MAKTMH, TENKTMH FROM KICHTHUOCMH WHERE ANHIEN = 1
		END
